version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d735dl42kvos7388bsi0-a.oregon-postgres.render.com:5432/leave_management_wajz
      - SPRING_DATASOURCE_USERNAME=leave_management_wajz_user
      - SPRING_DATASOURCE_PASSWORD=6ujroB27GKpb5rKiDqVEWNV12PKh5dT8
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
